"""public id migration

Revision ID: 256550a52475
Revises: 203e66eeba3e
Create Date: 2019-09-16 20:33:17.467449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '256550a52475'
down_revision = '203e66eeba3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('public_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'public_id')
    # ### end Alembic commands ###
