"""change picture id type

Revision ID: 27aa7fa2da85
Revises: 59662114c4b4
Create Date: 2019-11-27 00:07:32.253529

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '27aa7fa2da85'
down_revision = '59662114c4b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('picture', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=37))
    op.alter_column('user', 'admin',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'admin',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    op.alter_column('picture', 'id',
               existing_type=sa.String(length=37),
               type_=mysql.INTEGER(display_width=11))
    # ### end Alembic commands ###
