"""adds tag and picture models

Revision ID: 3de7816e7d57
Revises: 5ebd43b1729e
Create Date: 2019-10-29 00:19:34.696572

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3de7816e7d57'
down_revision = '5ebd43b1729e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('picture',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('path', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eventTag',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('event', sa.Column('picture_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'event', 'picture', ['picture_id'], ['id'])
    op.alter_column('request', 'status',
               existing_type=mysql.ENUM('approved', 'rejected', 'pending', collation='utf8mb4_unicode_ci'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('request', 'status',
               existing_type=mysql.ENUM('approved', 'rejected', 'pending', collation='utf8mb4_unicode_ci'),
               nullable=True)
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.drop_column('event', 'picture_id')
    op.drop_table('eventTag')
    op.drop_table('tag')
    op.drop_table('picture')
    # ### end Alembic commands ###
