"""adds subtitle field

Revision ID: 52e614ada366
Revises: aabe305d187c
Create Date: 2019-11-03 00:04:38.887941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52e614ada366'
down_revision = 'aabe305d187c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('subtitle', sa.String(length=60), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'subtitle')
    # ### end Alembic commands ###
