"""removed foregin key temprorily

Revision ID: 59662114c4b4
Revises: c163973e5090
Create Date: 2019-11-27 00:03:52.716511

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '59662114c4b4'
down_revision = 'c163973e5090'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('event_ibfk_2', 'event', type_='foreignkey')
    op.drop_column('picture', 'public_id')
    op.alter_column('user', 'admin',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'admin',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    op.add_column('picture', sa.Column('public_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=37), nullable=False))
    op.create_foreign_key('event_ibfk_2', 'event', 'picture', ['picture_id'], ['id'])
    # ### end Alembic commands ###
