"""created_at and updated_at fiields

Revision ID: 5ebd43b1729e
Revises: fd0e6aeae789
Create Date: 2019-09-21 05:38:26.603345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ebd43b1729e'
down_revision = 'fd0e6aeae789'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('created_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('event', sa.Column('updated_at', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'updated_at')
    op.drop_column('event', 'created_at')
    # ### end Alembic commands ###
