"""event migration

Revision ID: ae03f9ab3c7b
Revises: bcc5851197a7
Create Date: 2019-09-20 22:01:23.194934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae03f9ab3c7b'
down_revision = 'bcc5851197a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('created_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('user', sa.Column('updated_at', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'created_at')
    # ### end Alembic commands ###
