"""changed picture model

Revision ID: b9a7e0d6243e
Revises: b04c715a99c0
Create Date: 2019-11-26 23:28:36.768605

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b9a7e0d6243e'
down_revision = 'b04c715a99c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('picture', sa.Column('filename', sa.String(length=250), nullable=False))
    op.drop_column('picture', 'path')
    op.alter_column('tag', 'count',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tag', 'count',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.add_column('picture', sa.Column('path', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=250), nullable=False))
    op.drop_column('picture', 'filename')
    # ### end Alembic commands ###
